export function generateHMACSignature(secretKey: any, url: any, body: any, timestamp: any): any;
export function setCookie(name: any, value: any, expires: any, path: any): void;
export function getCookie(name: any): string;
export function deleteCookie(name: any, path: any): void;
export function getZaboSession(): string;
export function uuidValidate(uuid: any): boolean;
export function validateListParameters(limit: any, cursor: any): void;
export function validateEnumParameter(name: any, value: any, options: any, optional?: boolean): void;
export function createPaginator(payload: any, api: any): any;
export function sleep(milliseconds: any): any;
export const isBrowser: Function;
export const isNode: Function;
